### ISSUE TITLE
BUG: Return of the double-tokens

### ISSUE THREAD

**Issue by GambetTV** [javieros105/FVTT-TokenHUDWildcard#22]
This is an old bug that has returned with 1.5 of this module. When using the Wildcard Drop Default and placing a fresh token on the map, there will be two tokens placed on top of each other. This is most visible when changing the facing of the token, as only the top token will change facing, or when using Token Magic FX to place filters on tokens, as it will sometimes only place it on the top token, and other times it will double up the filters. I had to revert to 1.4 in the meantime.

**Comment by javieros105** [comment]
oh damn, gonna check it, probably happened with the way I fixed compatibility with Token Mold

**Comment by javieros105** [comment]
Btw what system are you using? because that's not happening with DnD5e afaik

**Comment by GambetTV** [comment]
I am using DnD5e. I went ahead and updated back to the most recent version to test it out, and have learned a couple things that might be useful to you.

1st: Copying and Pasting a token does not seem to cause the problem.
2nd: Dragging a token onto the map from the Actor's Directory is where the problem is caused, and happens I *think* under one specific circumstance.

First, the prototype token needs to have a default image set under Wildcard Drop Default. Now, if the last time you used that token, you were on the default image, then you probably won't have the problem the next time you drag the token. However, if the last time you used the token you selected a different image, then you will have the problem.

Furthermore, what I *think* is going on, is the default image is being projected onto the bottom, and cannot be adjusted, rotated, filters applied to it, etc. The top image is, I think a randomly generated one, which does not conform to the scaling prompts. So maybe the issue has something to do with the default image?

Once you manually change the image, the problem goes away BTW. It will crop back up if you drag a new token onto the map.

However, NOT ALWAYS. That's sorta the weird thing. For some reason sometimes the problem just fixes itself for a token, at least temporarily. However it will still be applied to other tokens, and usually refreshing will cause the problem to return for a token.

Hopefully this helps!

**Comment by javieros105** [comment]
Weird, I can't replicate the issue. Can you record a video of that problem happening? And if possible check if it's because another mod? Maybe when I fixed the problem for token mold i ruined it for another mod

**Comment by Dick-K** [comment]
Same problem for me, am using the Call of Cthulhu (Unofficial) system.

ETA: Tested with all other modules OFF, problem persists.

**Comment by GambetTV** [comment]
I just tested the problem with all other modules turned off on the DnD5e system, it still happens. I don't have a video, but I attached an image of a token freshly dragged onto the map from the Actor's Directory. I opened up the prototype token's settings so you can see the Image Path and Default Image are properly set. The Default Image is the one on the bottom. The one on the top is a random one, and is a different one every time I do it.

![image](https://user-images.githubusercontent.com/72000497/135789442-a786a5f3-8820-4e3d-ae81-40f5f829f9f1.png)

**Comment by GambetTV** [comment]
One thing I should point out is that the Token Configuration of the token on the map, not the prototype, is showing as having the Image Path of the bottom token, not the random top one.

**Comment by javieros105** [comment]
mmmmm super weird, I haven't been able to replicate the behaviour, but I'm thinking of just going back to the previous version and not try to fix the compatibility with token mold for now

**Comment by javieros105** [comment]
So sorry it's been such a long time. The error I suppose is till happening right?

**Comment by GambetTV** [comment]
Yes. I went back to version 1.4 until it's resolved. With Foundry version 9 out now it's probably time for an update anyway.

**Comment by javieros105** [comment]
@GambetTV  Can you check if with version 1.6.0 it still happens, I was never able to replicate this issue

**Comment by GambetTV** [comment]
It does not seem to be happening currently. Thank you!

**Comment by javieros105** [comment]
Awesome!
